#!/usr/bin/env python3
"""
Build css/fonts.css: three subsets of Fusion Pixel 12px (缝合像素字体, OFL-1.1,
https://github.com/TakWolf/fusion-pixel-font) embedded as woff2 data URIs.

  FP-SC  — Simplified-Chinese glyph forms; used for zh, en, es, it, de, ar (Latin part)
  FP-JP  — Japanese glyph forms; used for ja
  FP-KR  — Korean glyph forms; used for ko

Only the characters that actually appear in the UI are kept, so the whole file
stays small. Sources are the @fontsource npm packages; the script downloads
them from the npm registry into --src if they are not there yet.

    pip install fonttools brotli
    python3 tools/subset-fonts.py --src /path/to/cache
"""
import argparse, base64, io, json, os, re, subprocess, sys, tarfile, tempfile, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VARIANTS = {  # family name -> (npm package, i18n language codes whose strings it must cover)
    'FP-SC': ('fusion-pixel-12px-proportional-sc', ['zh', 'en', 'es', 'it', 'de', 'ar']),
    'FP-JP': ('fusion-pixel-12px-proportional-jp', ['ja']),
    'FP-KR': ('fusion-pixel-12px-proportional-kr', ['ko']),
}
ASCII = ''.join(chr(c) for c in range(0x20, 0x7F))
LATIN1 = ''.join(chr(c) for c in range(0xA0, 0x100))
SYMBOLS = '–—…·«»„“”‘’↓■▶●⚙→×°'


def lang_block(src, code):
    m = re.search(r'\n  %s: \{(.*?)\n  \},' % code, src, re.S)
    if not m:
        sys.exit(f'language block {code} not found in i18n.js')
    return m.group(1)


def fetch_package(pkg, dest):
    woff = os.path.join(dest, f'{pkg}.woff2')
    if os.path.exists(woff):
        return woff
    print(f'  downloading @fontsource/{pkg} …')
    meta = json.load(urllib.request.urlopen(f'https://registry.npmjs.org/@fontsource%2F{pkg}/latest'))
    data = urllib.request.urlopen(meta['dist']['tarball']).read()
    with tarfile.open(fileobj=io.BytesIO(data), mode='r:gz') as tf:
        for m in tf.getmembers():
            if m.name.endswith('-400-normal.woff2'):
                with open(woff, 'wb') as f:
                    f.write(tf.extractfile(m).read())
                return woff
    sys.exit(f'no woff2 in {pkg}')


def subset(src_woff, text, out_dir):
    out = os.path.join(out_dir, 'subset.woff2')
    txt = os.path.join(out_dir, 'chars.txt')
    with open(txt, 'w', encoding='utf-8') as f:
        f.write(text)
    subprocess.run([sys.executable, '-m', 'fontTools.subset', src_woff, f'--text-file={txt}',
                    '--flavor=woff2', f'--output-file={out}', '--layout-features=*', '--no-hinting',
                    '--name-IDs=*', '--notdef-outline'], check=True)
    with open(out, 'rb') as f:
        return f.read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', default=os.path.join(tempfile.gettempdir(), 'fusion-pixel-src'))
    args = ap.parse_args()
    os.makedirs(args.src, exist_ok=True)

    i18n = open(os.path.join(ROOT, 'js', 'i18n.js'), encoding='utf-8').read()
    extra = ''
    for rel in ('index.html', 'js/app.js'):
        extra += open(os.path.join(ROOT, rel), encoding='utf-8').read()

    css = ['/* generated by tools/subset-fonts.py — Fusion Pixel 12px (OFL-1.1) subsets */']
    total = 0
    for family, (pkg, codes) in VARIANTS.items():
        text = ASCII + LATIN1 + SYMBOLS
        for c in codes:
            text += lang_block(i18n, c)
        if family == 'FP-SC':
            text += extra
        chars = ''.join(sorted(set(ch for ch in text if not ch.isspace() or ch == ' ')))
        woff = fetch_package(pkg, args.src)
        with tempfile.TemporaryDirectory() as tmp:
            data = subset(woff, chars, tmp)
        total += len(data)
        b64 = base64.b64encode(data).decode('ascii')
        css.append(f"@font-face {{ font-family: '{family}'; font-style: normal; font-weight: 400; font-display: block;\n"
                   f"  src: url(data:font/woff2;base64,{b64}) format('woff2'); }}")
        print(f'  {family}: {len(chars)} chars → {len(data) // 1024} KB')
    out = os.path.join(ROOT, 'css', 'fonts.css')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(css) + '\n')
    print(f'wrote {out} ({total // 1024} KB of fonts)')


if __name__ == '__main__':
    main()
